name: 'Vue CI/CD with Docker and Nginx'

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: mytodo-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 使用适当的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Modify BASE_URL in quasar.config.js
        run: |
          sed -i 's|BASE_URL:.*|BASE_URL: '"'"'${{ secrets.BASE_URL }}'"'"',|' quasar.config.js

      - name: Build the project
        run: npx quasar build

      - name: Check if tag is vX.X.X
        id: check_tag
        run: |
          TAG=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\/v//') # 移除 tag 中的 'refs/tags/v'
          if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "IS_VERSION_TAG=true" >> $GITHUB_ENV
            echo "TAG_VERSION=$TAG" >> $GITHUB_ENV
          else
            echo "IS_VERSION_TAG=false" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        if: env.IS_VERSION_TAG == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and push1 (TAG_VERSION)
        if: env.IS_VERSION_TAG == 'true'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${TAG_VERSION} .
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${TAG_VERSION}

      - name: Build Docker image and push2 (latest)
        if: env.IS_VERSION_TAG == 'true'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${TAG_VERSION} ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

